name: Update GitHub Users Activity
on:
  schedule:
    - cron: "0 9 * * *" # Daily at 9AM UTC ("night time" in US/Pacific)
  push: 
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  update-github-users-activity:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download github-users-activity binaries
        uses: robinraju/release-downloader@v1
        with:
          repository: bryankaraffa/github-users-activity
          latest: true
          fileName: github-users-activity-*-linux-amd64
          token: ${{ secrets.BRYANKARAFFA_GITHUB_TOKEN }}

      - name: Download config
        uses: robinraju/release-downloader@v1
        with:
          repository: bryankaraffa/github-users-activity
          latest: true
          fileName: config.yaml
          token: ${{ secrets.BRYANKARAFFA_GITHUB_TOKEN }}

      - name: Make binaries executable
        run: |
          chmod +x $GITHUB_WORKSPACE/github-users-activity-*-linux-amd64

      - name: Run aggregator
        env:
          GITHUB_TOKEN_1: ${{ secrets.BRYANKARAFFA_GITHUB_TOKEN }}
          GITHUB_TOKEN_2: ${{ secrets.BKARAFFA_FLEXERA_GITHUB_TOKEN }}
        run: |
          $GITHUB_WORKSPACE/github-users-activity-aggregator-linux-amd64 > /dev/null 2>&1

      - name: Run visualizer
        run: |
          $GITHUB_WORKSPACE/github-users-activity-visualizer-linux-amd64

      - name: Move timeline.png to repo root
        run: |
          mv output/timeline.png timeline.png

      - name: Commit and push timeline.png
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: Automated update timeline.png
          file_pattern: timeline.png
          branch: main
